### ISSUE TITLE
Doesn't brings sammy main file

### ISSUE THREAD

**Issue by joaoeduardo** [ksmithut/bower-files#63]
I am trying to use this package with Sammy framework, but it doesn't bring the main file of this package. Here is my Gulp task:

```javascript
var bower  = require('bower-files')(),
    gulp   = require('gulp'),
    concat = require('gulp-concat'),
    csso   = require('gulp-csso'),
    less   = require('gulp-less'),
    purify = require('gulp-purifycss'),
    uglify = require('gulp-uglify');

gulp.task('style', function() {
    gulp.src(bower.self().ext(['css', 'less']).files)
        .pipe(less())
        .pipe(concat('app.css'))
        .pipe(csso())
        .pipe(gulp.dest('./public'));
});

gulp.task('script', function() {
    gulp.src(bower.self().ext('js').files)
        .pipe(concat('app.js'))
        .pipe(uglify())
        .pipe(gulp.dest('./public'));
});

gulp.task('default', ['style', 'script'], function() {});
```

**Comment by ksmithut** [comment]
It looks like their bower.json file has declared their main dependency file incorrectly. From their source:

```json
{
  ...
  "main": "/lib/sammy.js",
  ...
}
```

That path is an absolute path because it has a leading `/`. They need to remove that, and it will be included correctly. As a workaround, you can manually override their main declaration by adding the following to your own `bower.json`:

```json
{
  ...
  "overrides": {
    "sammy": {
      "main": "lib/sammy.js"
    }
  }
}
```

As a long term solution, I would open up an issue in their repository, point them to this issue and the example `bower.json` file found in [bower's documentation](http://bower.io/docs/creating-packages/)

**Comment by ksmithut** [comment]
@joaoeduardo Let me know if adding in the overrides in your `bower.json` fixes your problem.

**Comment by joaoeduardo** [comment]
Thank you. This fixed the problem. I will open an issue on Sammy project.
